language: go

go:
  - "1.11.x"
  - stable

os:
  - linux
  - osx

matrix:
  allow_failures:
    - name: "Benchmarks"
    - name: "Benchmarks extended"
  include:
  - name: "Benchmarks"
    language: go
    go: stable
    os: linux
    script:
      - "bash ./.travis/benchmark.sh"
  - name: "Benchmarks extended"
    language: go
    go: stable
    os: linux
    script:
      - "bash ./.travis/benchmark_extended.sh"

script:
  - "go build"
  - "go test -v"
  - "go test -run no_tests -bench ."
