language: go

go:
  - "1.11.x"
  - stable

os:
  - linux
  - osx

matrix:
  include:
    name: "Benchmarks"
    language: go
    go: stable
    os: linux
      - "bash ./.travis/benchmark.sh"

script:
  - "go build"
  - "go test -v"
  - "go test -run no_tests -bench ."
